import type { Metadata } from "next";
import { Poppins, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Page/Header/Header";
import Footer from "@/Components/Page/Footer/Footer";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allFonts = popins.className + " " + rubik.className;

  return (
    <html lang="en">
      <body className={allFonts}>
        <main className="flex min-h-screen flex-col bg-white_cold">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
